import TanstackProvider from "@/components/TanstackProvider";
import "../styles/globals.css";
import "tw-elements-react/dist/css/tw-elements-react.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/common/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// 이전 버전의 _app 파일의 역할을 대신함
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <TanstackProvider>
          {/* TODO: 공통 header적용 */}
          <Header />
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
};

export default RootLayout;
