import '../styles/globals.css';
// import "tw-elements-react/dist/css/tw-elements-react.min.css";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RouteHandler from '@/components/RouteHandler';
import Providers from '@/hooks/Provider';
import { AuthProvider } from '@/components/AuthProvider';
import Head from 'next/head';
import Header from '@/components/common/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'World Cup',
    description: 'Generated by create next app',
};
// 이전 버전의 _app 파일의 역할을 대신함
const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <>
            <html lang="en">
                {/* <head>
                    <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
                </head> */}
                <body className={inter.className} suppressHydrationWarning={true}>
                    <Providers>
                        <AuthProvider>
                            {/* TODO: 공통 header적용 */}
                            <Header />
                            <RouteHandler />
                            {children}
                        </AuthProvider>
                    </Providers>
                </body>
            </html>
        </>
    );
};

export default RootLayout;
